[build]
  command = "CI=false pnpm build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
