[build]
  command = "CI=false pnpm build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  CI = "false"
  # Note: Firebase environment variables must be set in Netlify dashboard
  # See ENVIRONMENT_SETUP.md for required variables

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
